# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 130)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("i2rightarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vlmain = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vlmain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vlmain.setSpacing(10)
        self.vlmain.setObjectName("vlmain")
        self.hlheader = QtWidgets.QHBoxLayout()
        self.hlheader.setObjectName("hlheader")
        self.header = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setScaledContents(False)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.hlheader.addWidget(self.header)
        self.vlmain.addLayout(self.hlheader)
        self.hlfile = QtWidgets.QHBoxLayout()
        self.hlfile.setObjectName("hlfile")
        self.lselectfpesfile = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lselectfpesfile.sizePolicy().hasHeightForWidth())
        self.lselectfpesfile.setSizePolicy(sizePolicy)
        self.lselectfpesfile.setObjectName("lselectfpesfile")
        self.hlfile.addWidget(self.lselectfpesfile)
        self.bselectfpesfile = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bselectfpesfile.sizePolicy().hasHeightForWidth())
        self.bselectfpesfile.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ifileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bselectfpesfile.setIcon(icon1)
        self.bselectfpesfile.setObjectName("bselectfpesfile")
        self.hlfile.addWidget(self.bselectfpesfile)
        self.leselectedfpesfile = QtWidgets.QLineEdit(self.centralwidget)
        self.leselectedfpesfile.setReadOnly(True)
        self.leselectedfpesfile.setObjectName("leselectedfpesfile")
        self.hlfile.addWidget(self.leselectedfpesfile)
        self.vlmain.addLayout(self.hlfile)
        self.hlbuildmodelhelp = QtWidgets.QHBoxLayout()
        self.hlbuildmodelhelp.setObjectName("hlbuildmodelhelp")
        self.bbuildmodel = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("iforward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bbuildmodel.setIcon(icon2)
        self.bbuildmodel.setObjectName("bbuildmodel")
        self.hlbuildmodelhelp.addWidget(self.bbuildmodel)
        self.bdoc = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bdoc.sizePolicy().hasHeightForWidth())
        self.bdoc.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ibook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bdoc.setIcon(icon3)
        self.bdoc.setObjectName("bdoc")
        self.hlbuildmodelhelp.addWidget(self.bdoc)
        self.vlmain.addLayout(self.hlbuildmodelhelp)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lstatus = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstatus.sizePolicy().hasHeightForWidth())
        self.lstatus.setSizePolicy(sizePolicy)
        self.lstatus.setObjectName("lstatus")
        self.horizontalLayout.addWidget(self.lstatus)
        self.lstatustext = QtWidgets.QLabel(self.centralwidget)
        self.lstatustext.setText("")
        self.lstatustext.setObjectName("lstatustext")
        self.horizontalLayout.addWidget(self.lstatustext)
        self.vlmain.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SESMoPy - SES Model Builder in Python3 / PyQt5"))
        self.header.setText(_translate("MainWindow", "SESMoPy - SES Model Builder for Python"))
        self.lselectfpesfile.setText(_translate("MainWindow", "Select an FPES JSON / XML File"))
        self.bselectfpesfile.setText(_translate("MainWindow", "Open FPES File"))
        self.bbuildmodel.setText(_translate("MainWindow", "Build Model"))
        self.bdoc.setText(_translate("MainWindow", "Documentation"))
        self.lstatus.setText(_translate("MainWindow", "Status: "))

